apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: rayleshh/argocd-app
  newTag: 6478717616073233498f436e5eee865454b3898f
