apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# configurations:
# - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
patches:
- path: ./transform_to_rollout.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: demo

resources:
- ./deployment.yaml
- ./service.yaml
